### ISSUE TITLE
Проверка списка (cons,map,sum,head,last)

### ISSUE THREAD

**Issue by LaraIsil** [psttf/TOOP#10]
(
[
nil = @list =>
  [        
            fold = @ this => \z => \f => z,
            cons = @ this => \a => this.fold := \z => \f => f a (this.fold z f),
            last = @ this => this.fold [] (\ x=> \ y=> x), 
            head = @ this => this.fold [] (\ x=> \y => y),
            sum = @ this => this.fold 0 (\a => \r => a + r ),
            app = @ this => \x => x+2,
            map = @ this => \f => this.fold [] (\a=>\r=> (f a) r) 
            
  ],
  main_head = @ this => (this.nil.cons (this.nil.app 1)).cons 2.cons 4.head,
  main_sum = @ this => (this.nil.cons 1).cons 2.cons (this.nil.app 4).sum,
  main_last = @ this => (this.nil.cons 1).cons 2.cons 4.last,
  main_map = @ this => ((this.nil.cons 1).cons 2.cons 4.map (this.nil.app))
  ].main_map
)

Насчёт map не уверена, но вроде бы правильно считает.

**Comment by psttf** [comment]
пример работает
