### ISSUE TITLE
Зависание на нумералах

### ISSUE THREAD

**Issue by psttf** [psttf/TOOP#4]
Интерпретатор виснет на подобном выражении, если вызывается больше двух `.succ`:
```
[
  zero = @ top => [
    case = @ this => \ z => \ s => z,
    succ = @ this => (this.case := \ z => \ s => s this).val := this.val + 1,
    val  = @ this => 0,
    pred = @ this => this.case (top.zero) (\ x => x)
  ],
  main = @ top => (top.zero.succ.succ.succ.succ.succ.pred).val
].main
```

**Comment by psttf** [comment]
в процессе получаются очень большие объекты: каждый вызов `succ` увеличивает объем кода втрое

**Comment by psttf** [comment]
следующий код без лямбд дает меньшие по объему объекты, но `val` вычисляется медленнее:
```
[
  zero = @ top => [
    case = @ this => [
        pred    = @ c => c,
        forpred = @ c => c,
        forzero = @ c => c,
        val     = @ c => c.forzero
    ],
    succ = @ this =>
        this
            .case := (this.case.pred := this)
            .val <= @ c => c.forpred,
    val  = @ this => ((this.case.forzero := 0).forpred <= @ c => c.pred.val + 1).val
  ],
  main = @ top => (top.zero.succ.succ.succ).val
].main
```

**Comment by Qwex** [comment]
На самом деле, при вызове succ объем кода в памяти  увеличивается не втрое, т.к. при подстановке this, подставляемый объект не копируется, а лишь подставляет ссылка на этот объект.

Но время вычислений растёт предположительно экспоненциально, по причине, что функция подстановки и вычисления теперь должна обойти все три вхождения одного и того же объекта this.

Поэтому в качестве возможной оптимизации есть две идеи:
1) (Сразу будет забраковано) Использовать императивный подход, чтобы изменять саму вершину абстрактного дерева (а не ссылку), и не создавать новый объект и новую ссылку.
2) Создать кэш ссылок на вершины, которые уже встречались при выполнении функции подстановки и вычисления, и если мы встречаем ссылку на объект, который ранее был изменён в ходе выполнения операции подстановки, то мы просто заменяем ссылку, а не выполняем новую подстановку.

Пример:
Пусть есть объект l1(ссылка на объект) = (\x => x + x) и объект a1 = App(\z => z, 5)  мы вычисляем следующий терм App(l1, a1), получим a1 + a1. Дальше у нас произойдёт вычисление значения аргументов. Но это два одинаковых объекта. И достаточно вычислить один раз a1, а вместо следующего вхождения a1 подставить вычисленное ранее значение. Тогда мы получим 5 + 5, но оба объекта 5 будут одним и тем же объектом, мы экономим и память и время на вычисления. В противном случае мы получим два объекта 5, которые дважды были вычислены.

Алгоритм получается несколько сложнее, чем казался первоначально, но думаю, что стоит подумать в этом направлении.

**Comment by psttf** [comment]
Да, надо поэкспериментировать. Может и императивный подход подойдет, если он доказанно работает без ошибок.

**Comment by Qwex** [comment]
Следующий код вычисляет порядка 3 секунд, независимо от количества вызовов метода succ, но метод pred здесь вынесен из объекта zero. Т.е. замедление возникает именно при передаче всей глобальной среды в локальный объект. 

Также при тестировании изменил в вычислениях все сравнения вида == на ссылочные сравнения вида eq, однако, на результате это вроде не сказалось.

[
  zero = @ top => [
    case = @ this => \ z => \ s => z,
    succ = @ this => (this.case := \ z => \ s => s this).val := this.val + 1,
    val  = @ this => 0
  ],
  pred = @ this => this.case (top.zero) (\ x => x),
  main = @ top => (top.zero.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ).val
].main

**Comment by Qwex** [comment]
Провел эксперимент с кэшированием множества свободных переменных в самом терме. Т.е. множество FV вычислял в момент создания терма.  И добавил ограничение, что подстановка проводится только в том случае, если переменная, на место которой производится подстановка, есть в множестве свободных переменных. В итоге, данные код:
[
numeral = @top => [
  zero = @ numeral => [
    case = @ zero => \ z => \ s => z,
    succ = @ zero => (zero.case :=  \ z => \ s => s zero).val := zero.val + 1,
    val  = @ zero => 0,
    pred = @ this => this.case (numeral.zero) (\ x => x)
  ]
],
main = @ top => (top.numeral.zero.succ.pred.succ.succ.succ.succ.pred.pred.pred.pred.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ.succ).val
].main

Вычисляется мгновенно. Т.е. главная проблема с производительностью кроется именно в операции подстановки.

Да, я здесь ещё разделил scope с описанием нумералов, от scope'а с методом main.

**Comment by Qwex** [comment]
Могу залить код в ветку Fix, чтобы его можно было посмотреть.
